spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iteck
  redis:
    host: localhost        # Redis 서버 호스트
    port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024 # 1KB 이상의 응답에 대해 압축
